## username & password reddit login pair
## use your throwaway account as slav.. I mean worker 
users = [
   {username="your_username_1", password="your_password_1"},
   {username="your_username_2", password="your_password_2"},
]

[image]
    path = "./ref.bmp"                  ## target image reference. file must be BMP & have color like in /r/place
    offset = { x = 915, y = 871}        ## Top Left Coordinate in /r/place
